# Generated by Django 4.0.6 on 2022-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, verbose_name='HomeBlog name1')),
                ('name2', models.CharField(max_length=50, verbose_name='HomeBlog name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeBlog image')),
                ('about1', models.TextField(verbose_name='HomeBlog about1')),
                ('about2', models.TextField(verbose_name='HomeBlog about2')),
            ],
            options={
                'verbose_name': 'HomeBlog',
                'verbose_name_plural': 'HomeBlogs',
            },
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
