# Generated by Django 4.0.6 on 2022-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_homeblog_delete_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblog',
            name='about1',
            field=models.TextField(null=True, verbose_name='HomeBlog about1'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='about2',
            field=models.TextField(null=True, verbose_name='HomeBlog about2'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='HomeBlog image'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='name1',
            field=models.CharField(max_length=50, null=True, verbose_name='HomeBlog name1'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='name2',
            field=models.CharField(max_length=50, null=True, verbose_name='HomeBlog name2'),
        ),
    ]
