# Generated by Django 4.0.6 on 2022-07-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_homeblog_about1_alter_homeblog_about2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefeatureitem',
            name='img',
        ),
        migrations.AddField(
            model_name='homefeatureitem',
            name='img1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Item image1'),
        ),
        migrations.AddField(
            model_name='homefeatureitem',
            name='img2',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Item image2'),
        ),
    ]
