# Generated by Django 4.0.6 on 2022-07-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_homefeatureitem_img_homefeatureitem_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefeatureitem',
            name='img2',
        ),
        migrations.AlterField(
            model_name='homefeatureitem',
            name='img1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Item image'),
        ),
    ]
