# Generated by Django 4.0.6 on 2022-07-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_homefeatureitem_img2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homefeatureitem',
            old_name='img1',
            new_name='img',
        ),
    ]
