# Generated by Django 4.0.6 on 2022-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_img1_homefeatureitem_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeShip image')),
            ],
            options={
                'verbose_name': 'HomeShip',
                'verbose_name_plural': 'HomeShips',
            },
        ),
    ]
