# Generated by Django 4.0.6 on 2022-07-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_homeship'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, verbose_name='HeadBlog name1')),
            ],
            options={
                'verbose_name': 'HomeBlog',
                'verbose_name_plural': 'HeadBlogs',
            },
        ),
        migrations.DeleteModel(
            name='HomeShip',
        ),
    ]
