# Generated by Django 4.0.6 on 2022-07-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_headblog_delete_homeship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headblog',
            options={'verbose_name': 'HeadBlog', 'verbose_name_plural': 'HeadBlogs'},
        ),
        migrations.RemoveField(
            model_name='homeblog',
            name='name1',
        ),
    ]
