# Generated by Django 4.0.6 on 2022-07-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_headblog_options_remove_homeblog_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HeadFooter name')),
                ('about', models.TextField(verbose_name='HeadFooter about')),
            ],
            options={
                'verbose_name': 'HeadFooter',
                'verbose_name_plural': 'HeadFooters',
            },
        ),
    ]
