# Generated by Django 4.0.6 on 2022-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, verbose_name='BlogSingle name1')),
                ('name2', models.CharField(max_length=50, verbose_name='BlogSingle name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='BlogSingle image')),
                ('about1', models.TextField(verbose_name='BlogSingle about1')),
                ('about2', models.TextField(verbose_name='BlogSingle about2')),
            ],
            options={
                'verbose_name': 'BlogSingle',
                'verbose_name_plural': 'BlogSingles',
            },
        ),
    ]
