# Generated by Django 4.0.6 on 2022-07-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_blogdavis'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogJanis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='BlogJanis about')),
                ('img', models.ImageField(upload_to='media', verbose_name='BlogJanis image')),
            ],
            options={
                'verbose_name': 'BlogeJanis',
                'verbose_name_plural': 'BlogsJanis',
            },
        ),
    ]
