# Generated by Django 4.0.6 on 2022-07-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_blogjanis'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomeContact name')),
            ],
            options={
                'verbose_name': 'HomeContact',
                'verbose_name_plural': 'HomeContacts',
            },
        ),
    ]
