# Generated by Django 4.0.6 on 2022-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_homecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='ShippingBlog image')),
            ],
            options={
                'verbose_name': 'ShoppingBlog',
                'verbose_name_plural': 'ShoppingBlogs',
            },
        ),
    ]
