# Generated by Django 4.0.6 on 2022-07-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_shippingblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingblog',
            options={'verbose_name': 'ShippingBlog', 'verbose_name_plural': 'ShippingBlogs'},
        ),
    ]
