# Generated by Django 4.0.6 on 2022-07-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_shippingblog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingblog',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='ShippingBlog name'),
        ),
    ]
