# Generated by Django 4.0.6 on 2022-07-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_shippingblog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ErrorBlog name')),
                ('img', models.ImageField(upload_to='media', verbose_name='ErrorBlog image')),
                ('about', models.TextField(verbose_name='ErrorBlog about')),
            ],
            options={
                'verbose_name': 'ErrorBlog',
                'verbose_name_plural': 'ErrorBlogs',
            },
        ),
    ]
