# Generated by Django 4.0.6 on 2022-07-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_errorblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopperLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='ShopperLogo image')),
            ],
            options={
                'verbose_name': 'ShopperLogo',
                'verbose_name_plural': 'ShopperLogos',
            },
        ),
    ]
