# Generated by Django 4.0.6 on 2022-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_shopperlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, verbose_name='Homecart name1')),
                ('name2', models.CharField(max_length=30, verbose_name='Homecart name2')),
                ('name3', models.CharField(max_length=30, verbose_name='Homecart name3')),
                ('name4', models.CharField(max_length=30, verbose_name='Homecart name4')),
                ('name5', models.CharField(max_length=30, verbose_name='Homecart name5')),
                ('name6', models.CharField(max_length=30, verbose_name='Homecart name6')),
                ('imag', models.ImageField(upload_to='media', verbose_name='HomeCart image')),
                ('about1', models.TextField(verbose_name='Homecart about1')),
                ('about2', models.TextField(verbose_name='Homecart about2')),
                ('about3', models.TextField(verbose_name='Homecart about3')),
                ('about4', models.TextField(verbose_name='Homecart about4')),
            ],
            options={
                'verbose_name': 'HomeCart',
                'verbose_name_plural': 'HomeCarts',
            },
        ),
    ]
