# Generated by Django 4.0.6 on 2022-07-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_homecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecart',
            name='about1',
            field=models.TextField(verbose_name='HomeCart about1'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='about2',
            field=models.TextField(verbose_name='HomeCart about2'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='about3',
            field=models.TextField(verbose_name='HomeCart about3'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='about4',
            field=models.TextField(verbose_name='HomeCart about4'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='name1',
            field=models.CharField(max_length=30, verbose_name='HomeCart name1'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='name2',
            field=models.CharField(max_length=30, verbose_name='HomeCart name2'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='name3',
            field=models.CharField(max_length=30, verbose_name='HomeCart name3'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='name4',
            field=models.CharField(max_length=30, verbose_name='HomeCart name4'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='name5',
            field=models.CharField(max_length=30, verbose_name='HomeCart name5'),
        ),
        migrations.AlterField(
            model_name='homecart',
            name='name6',
            field=models.CharField(max_length=30, verbose_name='HomeCart name6'),
        ),
    ]
