# Generated by Django 4.0.6 on 2022-07-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_homecart_about1_alter_homecart_about2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecart',
            old_name='imag',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='homecart',
            name='about3',
        ),
        migrations.RemoveField(
            model_name='homecart',
            name='about4',
        ),
        migrations.RemoveField(
            model_name='homecart',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='homecart',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='homecart',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='homecart',
            name='name6',
        ),
    ]
