# Generated by Django 4.0.6 on 2022-07-29 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_rename_imag_homecart_img_remove_homecart_about3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Car name')),
                ('title_hy', models.CharField(max_length=50, null=True, verbose_name='Car name')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Car name')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Car name')),
                ('text', models.TextField(verbose_name='Car text')),
                ('text_hy', models.TextField(null=True, verbose_name='Car text')),
                ('text_ru', models.TextField(null=True, verbose_name='Car text')),
                ('text_en', models.TextField(null=True, verbose_name='Car text')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.AddField(
            model_name='blogdavis',
            name='about_en',
            field=models.TextField(null=True, verbose_name='BlogDavis about'),
        ),
        migrations.AddField(
            model_name='blogdavis',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='BlogDavis about'),
        ),
        migrations.AddField(
            model_name='blogdavis',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='BlogDavis about'),
        ),
        migrations.AddField(
            model_name='blogdavis',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='BlogDavis name'),
        ),
        migrations.AddField(
            model_name='blogdavis',
            name='name_hy',
            field=models.CharField(max_length=20, null=True, verbose_name='BlogDavis name'),
        ),
        migrations.AddField(
            model_name='blogdavis',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='BlogDavis name'),
        ),
        migrations.AddField(
            model_name='blogjanis',
            name='about_en',
            field=models.TextField(null=True, verbose_name='BlogJanis about'),
        ),
        migrations.AddField(
            model_name='blogjanis',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='BlogJanis about'),
        ),
        migrations.AddField(
            model_name='blogjanis',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='BlogJanis about'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='about1_en',
            field=models.TextField(null=True, verbose_name='BlogSingle about1'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='about1_hy',
            field=models.TextField(null=True, verbose_name='BlogSingle about1'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='about1_ru',
            field=models.TextField(null=True, verbose_name='BlogSingle about1'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='about2_en',
            field=models.TextField(null=True, verbose_name='BlogSingle about2'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='about2_hy',
            field=models.TextField(null=True, verbose_name='BlogSingle about2'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='about2_ru',
            field=models.TextField(null=True, verbose_name='BlogSingle about2'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='name1_en',
            field=models.CharField(max_length=30, null=True, verbose_name='BlogSingle name1'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='name1_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='BlogSingle name1'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='name1_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='BlogSingle name1'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='name2_en',
            field=models.CharField(max_length=50, null=True, verbose_name='BlogSingle name2'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='name2_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='BlogSingle name2'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='name2_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='BlogSingle name2'),
        ),
        migrations.AddField(
            model_name='circle',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Circle about'),
        ),
        migrations.AddField(
            model_name='circle',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Circle about'),
        ),
        migrations.AddField(
            model_name='circle',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Circle about'),
        ),
        migrations.AddField(
            model_name='circle',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Circle name'),
        ),
        migrations.AddField(
            model_name='circle',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Circle name'),
        ),
        migrations.AddField(
            model_name='circle',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Circle name'),
        ),
        migrations.AddField(
            model_name='errorblog',
            name='about_en',
            field=models.TextField(null=True, verbose_name='ErrorBlog about'),
        ),
        migrations.AddField(
            model_name='errorblog',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='ErrorBlog about'),
        ),
        migrations.AddField(
            model_name='errorblog',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='ErrorBlog about'),
        ),
        migrations.AddField(
            model_name='errorblog',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='ErrorBlog name'),
        ),
        migrations.AddField(
            model_name='errorblog',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='ErrorBlog name'),
        ),
        migrations.AddField(
            model_name='errorblog',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='ErrorBlog name'),
        ),
        migrations.AddField(
            model_name='headblog',
            name='name1_en',
            field=models.CharField(max_length=30, null=True, verbose_name='HeadBlog name1'),
        ),
        migrations.AddField(
            model_name='headblog',
            name='name1_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='HeadBlog name1'),
        ),
        migrations.AddField(
            model_name='headblog',
            name='name1_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='HeadBlog name1'),
        ),
        migrations.AddField(
            model_name='headfooter',
            name='about_en',
            field=models.TextField(null=True, verbose_name='HeadFooter about'),
        ),
        migrations.AddField(
            model_name='headfooter',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='HeadFooter about'),
        ),
        migrations.AddField(
            model_name='headfooter',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='HeadFooter about'),
        ),
        migrations.AddField(
            model_name='headfooter',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='HeadFooter name'),
        ),
        migrations.AddField(
            model_name='headfooter',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='HeadFooter name'),
        ),
        migrations.AddField(
            model_name='headfooter',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='HeadFooter name'),
        ),
        migrations.AddField(
            model_name='homeblog',
            name='about1_en',
            field=models.TextField(null=True, verbose_name='HomeBlog about1'),
        ),
        migrations.AddField(
            model_name='homeblog',
            name='about1_hy',
            field=models.TextField(null=True, verbose_name='HomeBlog about1'),
        ),
        migrations.AddField(
            model_name='homeblog',
            name='about1_ru',
            field=models.TextField(null=True, verbose_name='HomeBlog about1'),
        ),
        migrations.AddField(
            model_name='homeblog',
            name='about2_en',
            field=models.TextField(null=True, verbose_name='HomeBlog about2'),
        ),
        migrations.AddField(
            model_name='homeblog',
            name='about2_hy',
            field=models.TextField(null=True, verbose_name='HomeBlog about2'),
        ),
        migrations.AddField(
            model_name='homeblog',
            name='about2_ru',
            field=models.TextField(null=True, verbose_name='HomeBlog about2'),
        ),
        migrations.AddField(
            model_name='homeblog',
            name='name2_en',
            field=models.CharField(max_length=50, null=True, verbose_name='HomeBlog name2'),
        ),
        migrations.AddField(
            model_name='homeblog',
            name='name2_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='HomeBlog name2'),
        ),
        migrations.AddField(
            model_name='homeblog',
            name='name2_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='HomeBlog name2'),
        ),
        migrations.AddField(
            model_name='homebrand',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Brand name'),
        ),
        migrations.AddField(
            model_name='homebrand',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Brand name'),
        ),
        migrations.AddField(
            model_name='homebrand',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Brand name'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='about1_en',
            field=models.TextField(null=True, verbose_name='HomeCart about1'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='about1_hy',
            field=models.TextField(null=True, verbose_name='HomeCart about1'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='about1_ru',
            field=models.TextField(null=True, verbose_name='HomeCart about1'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='about2_en',
            field=models.TextField(null=True, verbose_name='HomeCart about2'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='about2_hy',
            field=models.TextField(null=True, verbose_name='HomeCart about2'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='about2_ru',
            field=models.TextField(null=True, verbose_name='HomeCart about2'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='name1_en',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeCart name1'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='name1_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeCart name1'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='name1_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeCart name1'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='name2_en',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeCart name2'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='name2_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeCart name2'),
        ),
        migrations.AddField(
            model_name='homecart',
            name='name2_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeCart name2'),
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Carusel about'),
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Carusel about'),
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Carusel about'),
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='name1_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Carusel name'),
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='name1_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Carusel name'),
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='name1_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Carusel name'),
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='name2_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Carusel name'),
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='name2_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Carusel name'),
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='name2_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Carusel name'),
        ),
        migrations.AddField(
            model_name='homecategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='homecategory',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='homecategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='homecontact',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeContact name'),
        ),
        migrations.AddField(
            model_name='homecontact',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeContact name'),
        ),
        migrations.AddField(
            model_name='homecontact',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeContact name'),
        ),
        migrations.AddField(
            model_name='homefeatureitem',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Item about'),
        ),
        migrations.AddField(
            model_name='homefeatureitem',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Item about'),
        ),
        migrations.AddField(
            model_name='homefeatureitem',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Item about'),
        ),
        migrations.AddField(
            model_name='homerec',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Rec about'),
        ),
        migrations.AddField(
            model_name='homerec',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Rec about'),
        ),
        migrations.AddField(
            model_name='homerec',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Rec about'),
        ),
        migrations.AddField(
            model_name='homesubcategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='homesubcategory',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='homesubcategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='map',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Map name'),
        ),
        migrations.AddField(
            model_name='map',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Map name'),
        ),
        migrations.AddField(
            model_name='map',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Map name'),
        ),
        migrations.AddField(
            model_name='shippingblog',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ShippingBlog name'),
        ),
        migrations.AddField(
            model_name='shippingblog',
            name='name_hy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ShippingBlog name'),
        ),
        migrations.AddField(
            model_name='shippingblog',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ShippingBlog name'),
        ),
        migrations.AddField(
            model_name='shopperlogo',
            name='img_en',
            field=models.ImageField(null=True, upload_to='media', verbose_name='ShopperLogo image'),
        ),
        migrations.AddField(
            model_name='shopperlogo',
            name='img_hy',
            field=models.ImageField(null=True, upload_to='media', verbose_name='ShopperLogo image'),
        ),
        migrations.AddField(
            model_name='shopperlogo',
            name='img_ru',
            field=models.ImageField(null=True, upload_to='media', verbose_name='ShopperLogo image'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('img', models.ImageField(upload_to='media')),
                ('web_id', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('In not Stock', 'In not Stock')], max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Sale', 'Sale')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'orderproduct',
                'verbose_name_plural': 'orederproducts',
                'ordering': ['user_id'],
            },
        ),
    ]
